//! TurboMCP server macro implementation
//!
//! This macro provides ergonomic server creation by:
//! - Automatically discovering and registering #[tool], #[resource], and #[prompt] methods
//! - Generating a complete MCP server with zero boilerplate
//! - Integrating seamlessly with the existing builder pattern for advanced use cases
//! - Providing proper JSON schemas and Context injection
//! - Creating the essential run_stdio() method

use proc_macro::TokenStream;
use proc_macro2::Span;
use quote::quote;
use syn::{Ident, ItemImpl};

/// Generate the TurboMCP server implementation (idiomatic impl block pattern)
pub fn generate_server_impl(args: TokenStream, input_impl: ItemImpl) -> TokenStream {
    // Parse server attributes using world-class syn parsing
    let attrs = match crate::attrs::ServerAttrs::from_args(args) {
        Ok(attrs) => attrs,
        Err(e) => return e.to_compile_error().into(),
    };
    // Extract the struct name from the impl block
    let struct_name = match &*input_impl.self_ty {
        syn::Type::Path(type_path) => &type_path.path.segments.last().unwrap().ident,
        _ => {
            return syn::Error::new(
                proc_macro2::Span::call_site(),
                "The #[server] attribute only supports named types",
            )
            .to_compile_error()
            .into();
        }
    };

    // Analyze impl block for #[tool] methods
    let mut tool_methods = Vec::new();
    let mut tool_metadata_functions = Vec::new();
    let mut tool_handler_functions = Vec::new();

    for item in &input_impl.items {
        if let syn::ImplItem::Fn(method) = item {
            // Check if method has #[tool] attribute
            for attr in &method.attrs {
                if attr.path().is_ident("tool") {
                    let method_name = &method.sig.ident;
                    let metadata_fn_name = Ident::new(
                        &format!("__turbomcp_tool_metadata_{method_name}"),
                        Span::call_site(),
                    );
                    let handler_fn_name = Ident::new(
                        &format!("__turbomcp_tool_handler_{method_name}"),
                        Span::call_site(),
                    );
                    tool_methods.push(method_name.clone());
                    tool_metadata_functions.push(metadata_fn_name);
                    tool_handler_functions.push(handler_fn_name);
                    break;
                }
            }
        }
    }

    // Generate metadata function for testing and runtime
    let metadata_fn_name = Ident::new(
        &format!("__turbomcp_server_metadata_{struct_name}"),
        Span::call_site(),
    );

    let name_value = attrs
        .name
        .clone()
        .unwrap_or_else(|| struct_name.to_string());
    let version_value = attrs.version.clone().unwrap_or_else(|| "1.0.0".to_string());
    let description_value = match &attrs.description {
        Some(desc) => quote! { Some(#desc) },
        None => quote! { None },
    };

    // Generate roots configuration code using the attrs module
    let roots_config = attrs.generate_roots_config();

    // Prepare tool method data for router generation
    let tool_method_data: Vec<_> = tool_methods
        .iter()
        .zip(tool_metadata_functions.iter())
        .zip(tool_handler_functions.iter())
        .map(|((method, metadata), handler)| (method.clone(), metadata.clone(), handler.clone()))
        .collect();

    // Generate compile-time router
    let router_impl = crate::compile_time_router::generate_router(
        struct_name,
        &tool_method_data,
        &name_value,
        &version_value,
    );

    // Idiomatic implementation for impl blocks only
    let expanded = quote! {
        #input_impl

        impl #struct_name
        where
            Self: Clone,
        {
            /// Get server metadata (generated by macro)
            #[doc(hidden)]
            #[allow(non_snake_case)]
            pub fn #metadata_fn_name() -> (&'static str, &'static str, Option<&'static str>) {
                (#name_value, #version_value, #description_value)
            }

            /// Initialize context factory for this server
            fn create_context_factory() -> turbomcp::ContextFactory {
                use turbomcp::{ContextFactory, ContextFactoryConfig, Container};

                let config = ContextFactoryConfig::default();
                let container = Container::new();
                ContextFactory::new(config, container)
            }

            /// Tool discovery - collects all #[tool] methods
            fn discover_tools() -> Vec<(String, String, serde_json::Value)> {
                let mut tools = Vec::new();

                // Auto-discovered tools from #[tool] methods with real schemas
                #(
                    {
                        let (name, description, schema) = Self::#tool_metadata_functions();
                        tools.push((
                            name.to_string(),
                            description.to_string(),
                            schema
                        ));
                    }
                )*

                tools
            }

            /// Get all tools metadata for testing and validation
            ///
            /// Returns a vector of (name, description, schema) tuples for all registered tools.
            /// This is essential for integration testing and validating schema generation.
            pub fn get_tools_metadata() -> Vec<(String, String, serde_json::Value)> {
                Self::discover_tools()
            }

            /// Create server and get shutdown handle for graceful termination
            ///
            /// Essential for production deployments, container orchestration, and coordinated
            /// system shutdown. Returns both the server and a handle for external control.
            pub fn into_server_with_shutdown(self) -> Result<(turbomcp::Server, turbomcp::ShutdownHandle), turbomcp::ServerError> {
                let server = self.create_server()?;
                let shutdown_handle = server.shutdown_handle();
                Ok((server, shutdown_handle))
            }

            /// Get a shutdown handle for graceful server termination (legacy method)
            ///
            /// Essential for production deployments, container orchestration, and coordinated
            /// system shutdown. Enables external control over server lifecycle.
            pub fn shutdown_handle(&self) -> Result<turbomcp::ShutdownHandle, turbomcp::ServerError> {
                // For compatibility, we clone self to create the server
                // This works because the actual tool implementations will be captured properly
                let server = self.clone().create_server()?;
                Ok(server.shutdown_handle())
            }

            // Transport methods (run_stdio, run_http, etc.) are generated by compile_time_router
            // to avoid lifetime issues and provide maximum performance through static dispatch

            /// Create and configure the underlying server instance
            fn create_server(self) -> Result<turbomcp::Server, turbomcp::ServerError> {
                use turbomcp::{RequestContext, ServerBuilder};
                use turbomcp::handlers::utils;
                use turbomcp::{CallToolRequest, CallToolResult, Content, TextContent};

                // Create server builder with metadata from macro
                let mut builder = ServerBuilder::new()
                    .name(#name_value)
                    .version(#version_value);

                // Configure roots if specified in macro
                #roots_config

                // Tool auto-discovery and registration with actual method calls
                let server_instance = self;

                #(
                    {
                        let instance = server_instance.clone();
                        let (tool_name, tool_description, schema) = Self::#tool_metadata_functions();
                        let tool_handler = utils::tool_with_schema(
                            tool_name,
                            tool_description,
                            schema,
                            move |req: CallToolRequest, ctx: RequestContext| {
                                let instance = instance.clone();
                                async move {
                                    // Call the actual generated handler method
                                    instance.#tool_handler_functions(req, ctx).await
                                }
                            }
                        );
                        builder = builder.tool(tool_name, tool_handler)?;
                    }
                )*

                // If no tools discovered, provide helpful example
                if Self::discover_tools().is_empty() {
                    builder = builder.tool(
                        "example",
                        utils::tool(
                            "example",
                            "Example tool - Add #[tool] methods for auto-registration",
                            |_req: CallToolRequest, _ctx: RequestContext| async move {
                                Ok(CallToolResult {
                                    content: vec![Content::Text(TextContent {
                                        text: "Server running! Add #[tool] methods for automatic registration.".to_string(),
                                        annotations: None,
                                        meta: None,
                                    })],
                                    is_error: None,
                                })
                            }
                        )
                    )?;
                }

                Ok(builder.build())
            }

            /// Get server builder for advanced use cases
            pub fn builder() -> turbomcp::ServerBuilder {
                turbomcp::ServerBuilder::new()
                    .name(#name_value)
                    .version(#version_value)
            }

            /// Test a tool call directly for testing
            ///
            /// This function enables direct testing of tool handlers without requiring
            /// full server initialization or transport layer setup.
            pub async fn test_tool_call(
                &self,
                tool_name: &str,
                arguments: serde_json::Value
            ) -> Result<turbomcp::CallToolResult, turbomcp::ServerError> {
                use turbomcp::{CallToolRequest, RequestContext};
                use std::collections::HashMap;

                // Convert JSON arguments to HashMap<String, Value>
                let args_map = if arguments.is_object() {
                    arguments.as_object()
                        .map(|obj| {
                            let mut map = HashMap::new();
                            for (k, v) in obj {
                                map.insert(k.clone(), v.clone());
                            }
                            map
                        })
                } else {
                    None
                };

                let request = CallToolRequest {
                    name: tool_name.to_string(),
                    arguments: args_map,
                };

                let ctx = RequestContext::new();

                // Find and call the appropriate handler
                #(
                    if tool_name == stringify!(#tool_methods) {
                        return self.#tool_handler_functions(request, ctx).await;
                    }
                )*

                Err(turbomcp::ServerError::handler(format!("Tool '{}' not found", tool_name)))
            }

            /// Get server information (for integration with other systems)
            pub fn server_info() -> (&'static str, &'static str, Option<&'static str>) {
                (#name_value, #version_value, #description_value)
            }

        }

        // Add compile-time router implementation
        #router_impl
    };

    TokenStream::from(expanded)
}
